from fifteen_state_class import State

def heuristic(s: State) -> int:
    manhattan_dist = 0
    linear_conflicts = 0

    # The previous WEIGHT_FACTOR = 2.0 yielded a cost_ratio of 1.367.
    # To further reduce generated nodes while staying below the 1.80 cost_ratio limit,
    # we can increase the weighting factor. A factor of 2.5 is estimated to result
    # in a cost_ratio around 1.70, which is safely within the 1.80 bound.
    WEIGHT_FACTOR = 2.5

    # Calculate Manhattan Distance
    for i, val in enumerate(s.tiles):
        if val == 0:
            continue # Ignore the blank tile for Manhattan distance
        goal_r, goal_c = divmod(val, 4)
        cur_r, cur_c = divmod(i, 4)
        manhattan_dist += abs(goal_r - cur_r) + abs(goal_c - cur_c)

    # Calculate Linear Conflicts
    # Row Conflicts
    for r in range(4):
        # Collect tiles in this row that belong to this row in the goal state
        row_tiles_in_goal_row = [] # Stores (tile_value, current_column)
        for c in range(4):
            idx = r * 4 + c
            val = s.tiles[idx]
            if val == 0:
                continue # Ignore the blank tile for linear conflicts
            goal_r, goal_c = divmod(val, 4)
            if goal_r == r: # Tile val belongs to this row 'r' in the goal state
                row_tiles_in_goal_row.append((val, c))

        # Check for conflicts within this row
        # A conflict exists if two tiles are in their goal row but are reversed
        # in order relative to their goal columns.
        for i in range(len(row_tiles_in_goal_row)):
            for j in range(i + 1, len(row_tiles_in_goal_row)):
                tile_a_val, tile_a_cur_c = row_tiles_in_goal_row[i]
                tile_b_val, tile_b_cur_c = row_tiles_in_goal_row[j]

                tile_a_goal_c = tile_a_val % 4
                tile_b_goal_c = tile_b_val % 4

                if (tile_a_cur_c < tile_b_cur_c and tile_a_goal_c > tile_b_goal_c) or \
                   (tile_a_cur_c > tile_b_cur_c and tile_a_goal_c < tile_b_goal_c):
                    linear_conflicts += 1

    # Column Conflicts
    for c in range(4):
        # Collect tiles in this column that belong to this column in the goal state
        col_tiles_in_goal_col = [] # Stores (tile_value, current_row)
        for r in range(4):
            idx = r * 4 + c
            val = s.tiles[idx]
            if val == 0:
                continue # Ignore the blank tile for linear conflicts
            goal_r, goal_c = divmod(val, 4)
            if goal_c == c: # Tile val belongs to this column 'c' in the goal state
                col_tiles_in_goal_col.append((val, r))

        # Check for conflicts within this column
        # A conflict exists if two tiles are in their goal column but are reversed
        # in order relative to their goal rows.
        for i in range(len(col_tiles_in_goal_col)):
            for j in range(i + 1, len(col_tiles_in_goal_col)):
                tile_a_val, tile_a_cur_r = col_tiles_in_goal_col[i]
                tile_b_val, tile_b_cur_r = col_tiles_in_goal_col[j]

                tile_a_goal_r = tile_a_val // 4
                tile_b_goal_r = tile_b_val // 4

                if (tile_a_cur_r < tile_b_cur_r and tile_a_goal_r > tile_b_goal_r) or \
                   (tile_a_cur_r > tile_b_cur_r and tile_a_goal_r < tile_b_goal_r):
                    linear_conflicts += 1

    # The standard admissible linear conflict heuristic adds 2 for each conflict.
    # We combine Manhattan distance and (2 * Linear Conflicts) for the base admissible estimate.
    base_admissible_h = manhattan_dist + (linear_conflicts * 2)

    # Apply the weighting factor to make the heuristic non-admissible and greedier,
    # which helps reduce the number of unique nodes generated by A* search.
    # The int() cast truncates the result, ensuring a non-negative integer return value.
    return int(base_admissible_h * WEIGHT_FACTOR)